FROM debian:bullseye


RUN apt-get -y update \
	&& apt-get -y upgrade \
	&& apt-get -y install nginx-full

RUN apt-get -y install curl net-tools openssl

RUN openssl req -x509 -nodes -out ${CERTS_PATH} -keyout /etc/nginx/ssl/NG.key -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42/CN=saboulal.42.fr/UID=saboulal"

EXPOSE 443

COPY ./conf/nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /var/www/html && \
	chmod -R 755 /var/www/html

CMD ["nginx", "-g", "daemon off;"]
